development:
  oauth_consumer_key: tavzs2M0QRwE
  oauth_consumer_secret: KfMPM6baYDRMHi2a8XYn3urRc925KwcY
  base_url: "https://fireeagle.yahooapis.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://updatelocationapp.local/oauth_callback"
test:
  oauth_consumer_key: 8FOxWj1gKf8KeNAsoCFSIQ
  oauth_consumer_secret: Not99Co4IK8nL0x9jo3KdVpMVeof9iCvCR3q3KAqO0
  base_url: "https://fireeagle.yahooapis.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
production:
  oauth_consumer_key: 8FOxWj1gKf8KeNAsoCFSIQ
  oauth_consumer_secret: Not99Co4IK8nL0x9jo3KdVpMVeof9iCvCR3q3KAqO0 
  authorize_path: "/oauth/authenticate"
  base_url: "https://fireeagle.yahooapis.com"
  api_timeout: 10
  remember_for: 14 # days

